import type { Product, Category, Tag, Offer, Post } from "./types";

export const MOCK_CATEGORIES: Category[] = [
  {
    id: "sweets",
    slug: "sweets",
    name: "Sweets",
    description: "Traditional ghee sweets, made fresh in small batches.",
    image: "/images/categories/sweets.svg",
    order: 1,
  },
  {
    id: "snacks",
    slug: "snacks",
    name: "Snacks",
    description: "Crunchy savoury snacks and mixtures for every tea time.",
    image: "/images/categories/snacks.svg",
    order: 2,
  },
  {
    id: "special-combos",
    slug: "special-combos",
    name: "Special Combos",
    description: "Curated sweet and savoury combos for gifting and sharing.",
    image: "/images/categories/special-combos.svg",
    order: 3,
  },
  {
    id: "veg-pickles",
    slug: "veg-pickles",
    name: "Veg Pickles",
    description: "Traditional homestyle vegetarian pickles made with fresh ingredients.",
    image: "/images/categories/veg-pickles.svg",
    order: 4,
  },
  {
    id: "nonveg-pickles",
    slug: "nonveg-pickles",
    name: "Nonveg Pickles",
    description: "Spicy, rich, and delicious non-vegetarian pickles.",
    image: "/images/categories/nonveg-pickles.svg",
    order: 5,
  },
  {
    id: "podis",
    slug: "podis",
    name: "Podis",
    description: "Traditional spice powders and dry chutneys to elevate your meals.",
    image: "/images/categories/podis.svg",
    order: 6,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "bandar-halwa-pieces",
    slug: "bandar-halwa-pieces",
    name: "Bandar Halwa(Pieces)",
    description: "Rich, semi-translucent traditional Bandar Halwa cut into square pieces. Made with premium ingredients and pure ghee.",
    category: "sweets",
    categories: ["sweets"],
    categoryLabel: "Sweets",
    images: [
      "/images/products/bandar-halwa-pieces.png",
      "https://player.vimeo.com/external/435674703.sd.mp4?s=7fdf27e2213e4b77f98c8d8b671a53c9e6d0a7a0&profile_id=165&oauth2_token_id=57447761",
      "/images/tapeswaram_kaja_reel.png",
      "/images/madatha_kaja_reel.png"
    ],
    variants: [
      { id: "halwa-pieces-250g", label: "250gms", price: 290, mrp: 340, stock: 50 },
      { id: "halwa-pieces-500g", label: "500gms", price: 580, mrp: 680, stock: 50 },
      { id: "halwa-pieces-1kg", label: "1kg", price: 1160, mrp: 1360, stock: 50 },
    ],
    tags: ["best-seller", "top-pick"],
    rating: 5.0,
    reviewCount: 6,
    active: true,
    badges: ["100% Pure Veg", "Pure Ghee", "Traditional"],
  },
  {
    id: "agra-mixture",
    slug: "agra-mixture",
    name: "Agra Mixture",
    description: "Crunchy, savoury Agra-style mixture with the perfect balance of spice and crunch.",
    category: "snacks",
    categories: ["snacks"],
    categoryLabel: "Snacks",
    images: [
      "/images/products/namkeen-placeholder.svg",
      "https://player.vimeo.com/external/384761655.sd.mp4?s=38dbbb615015b6510f22d64a27546522c0627d7e&profile_id=165&oauth2_token_id=57447761",
      "/images/special_mixture_reel.png",
      "/images/ghee_ladoo_reel.png"
    ],
    variants: [
      { id: "agra-mixture-250g", label: "250 g", price: 120, mrp: 142, stock: 50 },
      { id: "agra-mixture-500g", label: "500 g", price: 240, mrp: 283, stock: 50 },
    ],
    tags: ["best-seller", "top-pick"],
    rating: 4.8,
    reviewCount: 176,
    active: true,
    badges: ["100% Pure Veg", "No Artificial Flavour"],
  },
  {
    id: "bandar-halwa-loose",
    slug: "bandar-halwa-loose",
    name: "Bandar Halwa Loose",
    description: "Authentic, rich, and mouth-watering Bandar Halwa in its traditional loose round disk format.",
    category: "sweets",
    categories: ["sweets"],
    categoryLabel: "Sweets",
    images: [
      "/images/products/bandar-halwa-loose.png",
      "https://player.vimeo.com/external/435674703.sd.mp4?s=7fdf27e2213e4b77f98c8d8b671a53c9e6d0a7a0&profile_id=165&oauth2_token_id=57447761",
      "/images/tapeswaram_kaja_reel.png",
      "/images/madatha_kaja_reel.png"
    ],
    variants: [
      { id: "halwa-loose-250g", label: "250gms", price: 305, mrp: 360, stock: 50 },
      { id: "halwa-loose-500g", label: "500gms", price: 610, mrp: 720, stock: 50 },
      { id: "halwa-loose-1kg", label: "1kg", price: 1220, mrp: 1440, stock: 50 },
    ],
    tags: ["best-seller"],
    rating: 3.0,
    reviewCount: 1,
    active: true,
    badges: ["100% Pure Veg", "Pure Ghee"],
  },
  {
    id: "flower-janthukulu",
    slug: "flower-janthukulu",
    name: "Flower Janthukulu",
    description: "Crispy flower janthukulu, a crunchy South-Indian tea-time favourite.",
    category: "snacks",
    categories: ["snacks"],
    categoryLabel: "Snacks",
    images: [
      "/images/products/namkeen-placeholder.svg",
      "https://player.vimeo.com/external/384761655.sd.mp4?s=38dbbb615015b6510f22d64a27546522c0627d7e&profile_id=165&oauth2_token_id=57447761",
      "/images/special_mixture_reel.png",
      "/images/ghee_ladoo_reel.png"
    ],
    variants: [
      { id: "flower-janthukulu-250g", label: "250 g", price: 110, mrp: 130, stock: 40 },
    ],
    tags: ["best-seller"],
    rating: 4.6,
    reviewCount: 64,
    active: true,
    badges: ["100% Pure Veg"],
  },
  {
    id: "chakidalu",
    slug: "chakidalu",
    name: "Chakidalu",
    description: "Hand-twisted chakidalu (chakli), crunchy and mildly spiced.",
    category: "snacks",
    categories: ["snacks"],
    categoryLabel: "Snacks",
    images: [
      "/images/products/namkeen-placeholder.svg",
      "https://player.vimeo.com/external/384761655.sd.mp4?s=38dbbb615015b6510f22d64a27546522c0627d7e&profile_id=165&oauth2_token_id=57447761",
      "/images/special_mixture_reel.png",
      "/images/ghee_ladoo_reel.png"
    ],
    variants: [
      { id: "chakidalu-250g", label: "250 g", price: 100, stock: 40 },
    ],
    tags: ["top-pick"],
    rating: 4.7,
    reviewCount: 58,
    active: true,
    badges: ["100% Pure Veg"],
  },
  {
    id: "bandar-laddu",
    slug: "bandar-laddu",
    name: "Bandar Laddu",
    description: "Traditional soft and smooth golden Bandar Laddus made with premium chickpea flour and pure ghee.",
    category: "sweets",
    categories: ["sweets"],
    categoryLabel: "Sweets",
    images: [
      "/images/products/bandar-laddu.png",
      "https://player.vimeo.com/external/435674703.sd.mp4?s=7fdf27e2213e4b77f98c8d8b671a53c9e6d0a7a0&profile_id=165&oauth2_token_id=57447761",
      "/images/tapeswaram_kaja_reel.png",
      "/images/madatha_kaja_reel.png"
    ],
    variants: [
      { id: "laddu-250g", label: "250gm", price: 285, mrp: 330, stock: 50 },
      { id: "laddu-500g", label: "500gm", price: 570, mrp: 660, stock: 50 },
      { id: "laddu-1kg", label: "1kg", price: 1140, mrp: 1320, stock: 50 },
    ],
    tags: ["best-seller", "top-pick"],
    rating: 4.9,
    reviewCount: 48,
    active: true,
    badges: ["100% Pure Veg", "Pure Ghee"],
  },
  {
    id: "kova-kajjikayalu",
    slug: "kova-kajjikayalu",
    name: "Kova Kajjikayalu",
    description: "Stuffed sweet kova rolls loaded with traditional flavours and premium ingredients.",
    category: "sweets",
    categories: ["sweets"],
    categoryLabel: "Sweets",
    images: [
      "/images/products/kova-kajjikayalu.png",
      "https://player.vimeo.com/external/435674703.sd.mp4?s=7fdf27e2213e4b77f98c8d8b671a53c9e6d0a7a0&profile_id=165&oauth2_token_id=57447761",
      "/images/tapeswaram_kaja_reel.png",
      "/images/madatha_kaja_reel.png"
    ],
    variants: [
      { id: "kova-250g", label: "250gms", price: 220, mrp: 260, stock: 50 },
      { id: "kova-500g", label: "500gms", price: 440, mrp: 520, stock: 50 },
      { id: "kova-1kg", label: "1kg", price: 880, mrp: 1040, stock: 50 },
    ],
    tags: ["top-pick"],
    rating: 3.5,
    reviewCount: 2,
    active: true,
    badges: ["100% Pure Veg", "Pure Milk Kova"],
  },
  {
    id: "avakai-mango-pickle",
    slug: "avakai-mango-pickle",
    name: "Avakai Mango Pickle",
    description: "Traditional Andhra Avakai Mango Pickle made with premium raw mangoes and hand-pressed oils.",
    category: "veg-pickles",
    categories: ["veg-pickles"],
    categoryLabel: "Veg Pickles",
    images: [
      "/images/products/namkeen-placeholder.svg",
      "https://player.vimeo.com/external/384761655.sd.mp4?s=38dbbb615015b6510f22d64a27546522c0627d7e&profile_id=165&oauth2_token_id=57447761",
      "/images/special_mixture_reel.png",
      "/images/ghee_ladoo_reel.png"
    ],
    variants: [
      { id: "avakai-mango-250g", label: "250 g", price: 150, stock: 100 },
      { id: "avakai-mango-500g", label: "500 g", price: 280, stock: 100 },
    ],
    tags: ["best-seller"],
    rating: 4.8,
    reviewCount: 112,
    active: true,
    badges: ["100% Pure Veg", "Homestyle", "No Preservatives"],
  },
  {
    id: "spicy-chicken-pickle",
    slug: "spicy-chicken-pickle",
    name: "Spicy Chicken Pickle",
    description: "Authentic, mouthwatering spicy chicken pickle made with tender chicken chunks and traditional spices.",
    category: "nonveg-pickles",
    categories: ["nonveg-pickles"],
    categoryLabel: "Nonveg Pickles",
    images: [
      "/images/products/namkeen-placeholder.svg",
      "https://player.vimeo.com/external/384761655.sd.mp4?s=38dbbb615015b6510f22d64a27546522c0627d7e&profile_id=165&oauth2_token_id=57447761",
      "/images/special_mixture_reel.png",
      "/images/ghee_ladoo_reel.png"
    ],
    variants: [
      { id: "chicken-pickle-250g", label: "250 g", price: 299, stock: 45 },
      { id: "chicken-pickle-500g", label: "500 g", price: 550, stock: 30 },
    ],
    tags: ["top-pick"],
    rating: 4.9,
    reviewCount: 84,
    active: true,
    badges: ["Spicy", "Premium Chicken", "Made Fresh"],
  },
  {
    id: "idli-karam-podi",
    slug: "idli-karam-podi",
    name: "Idli Karam Podi",
    description: "Traditional spicy lentil powder, perfect with ghee on hot idlis and dosas.",
    category: "podis",
    categories: ["podis"],
    categoryLabel: "Podis",
    images: [
      "/images/products/namkeen-placeholder.svg",
      "https://player.vimeo.com/external/384761655.sd.mp4?s=38dbbb615015b6510f22d64a27546522c0627d7e&profile_id=165&oauth2_token_id=57447761",
      "/images/special_mixture_reel.png",
      "/images/ghee_ladoo_reel.png"
    ],
    variants: [
      { id: "idli-podi-250g", label: "250 g", price: 99, stock: 120 },
    ],
    tags: ["best-seller"],
    rating: 4.7,
    reviewCount: 96,
    active: true,
    badges: ["100% Pure Veg", "Traditional Recipe"],
  },
];

export const MOCK_TAGS: Tag[] = [
  { id: "best-seller", slug: "best-seller", name: "Best Sellers", featured: true, order: 1 },
  { id: "top-pick", slug: "top-pick", name: "Top Picks", featured: true, order: 2 },
  { id: "new", slug: "new", name: "New Arrivals", featured: true, order: 3 },
];

export const MOCK_OFFERS: Offer[] = [
  {
    id: "welcome50",
    code: "WELCOME50",
    title: "₹50 Off Welcome Offer",
    description: "Get flat ₹50 off on your first order above ₹500",
    type: "flat",
    value: 50,
    minSubtotal: 500,
    active: true,
  },
  {
    id: "freeship",
    code: "FREESHIP",
    title: "Free Shipping",
    description: "Free shipping on orders above ₹700",
    type: "free_shipping",
    value: 0,
    minSubtotal: 700,
    active: true,
  },
];

export const MOCK_POSTS: Post[] = [
  {
    id: "post-1",
    slug: "making-of-pure-ghee-sweets",
    title: "The Art of Making Pure Ghee Sweets",
    excerpt: "Discover the traditional secrets behind our rich, melt-in-your-mouth sweets made with 100% pure ghee.",
    author: "Store Chef",
    cover: "/images/ghee_ladoo_reel.png",
    date: "2026-06-01",
    readMinutes: 5,
    content: [
      "Sweets are not just desserts; they are a part of our heritage and celebrations. At Bhaktanjaneya Sweets, we continue the legacy by choosing premium ingredients.",
      "The secret to the perfect texture and aroma lies in using pure cow ghee, slow-cooking in small batches, and giving the sweet the exact resting time it needs.",
    ],
    active: true,
  },
];