export const STATE_DISTRICTS: Record<string, string[]> = {
  "Andhra Pradesh": [
    "Visakhapatnam",
    "Vijayawada",
    "Rajahmundry",
    "Kakinada",
    "Guntur",
    "Nellore",
    "Tirupati",
    "Kurnool",
    "Anantapur",
    "Kadapa",
    "Eluru",
    "Ongole",
    "Srikakulam",
    "Vizianagaram",
    "Machilipatnam",
    "Tenali",
    "Bhimavaram",
    "Tadepalligudem",
    "Narasaraopet",
    "Chittoor",
    "Alluri Sitharama Raju",
    "Anakapalli",
    "Annamayya",
    "Bapatla",
    "Dr. B.R. Ambedkar Konaseema",
    "East Godavari",
    "Krishna",
    "Nandyal",
    "NTR",
    "Palnadu",
    "Parvathipuram Manyam",
    "Prakasam",
    "Sri Potti Sriramulu Nellore",
    "Sri Sathya Sai",
    "West Godavari",
    "YSR",
  ],
  Telangana: [
    "Hyderabad",
    "Secunderabad",
    "Warangal",
    "Hanamkonda",
    "Karimnagar",
    "Nizamabad",
    "Khammam",
    "Mahabubnagar",
    "Siddipet",
    "Suryapet",
    "Nalgonda",
    "Adilabad",
    "Ramagundam",
    "Bhadradri Kothagudem",
    "Jagtial",
    "Jangaon",
    "Jayashankar Bhupalpally",
    "Jogulamba Gadwal",
    "Kamareddy",
    "Komaram Bheem Asifabad",
    "Mahabubabad",
    "Mancherial",
    "Medak",
    "Medchal Malkajgiri",
    "Mulugu",
    "Nagarkurnool",
    "Narayanpet",
    "Nirmal",
    "Peddapalli",
    "Rajanna Sircilla",
    "Rangareddy",
    "Sangareddy",
    "Vikarabad",
    "Wanaparthy",
    "Yadadri Bhuvanagiri",
  ],
  Karnataka: [
    "Bengaluru",
    "Mysuru",
    "Mangaluru",
    "Hubballi",
    "Belagavi",
    "Kalaburagi",
    "Davanagere",
    "Ballari",
    "Vijayapura",
    "Shivamogga",
    "Tumakuru",
    "Raichur",
    "Udupi",
    "Bidar",
    "Hassan",
    "Mandya",
    "Chikkamagaluru",
  ],
  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
    "Tirunelveli",
    "Erode",
    "Vellore",
    "Thanjavur",
    "Tuticorin",
    "Dindigul",
    "Kanchipuram",
    "Nagercoil",
    "Cuddalore",
    "Kumbakonam",
  ],
  Maharashtra: [
    "Mumbai",
    "Pune",
    "Nagpur",
    "Thane",
    "Pimpri-Chinchwad",
    "Nashik",
    "Kalyan-Dombivli",
    "Vasai-Virar",
    "Aurangabad",
    "Navi Mumbai",
    "Solapur",
    "Kolhapur",
    "Amravati",
    "Nanded",
    "Jalgaon",
    "Sangli",
  ],
  Kerala: [
    "Thiruvananthapuram",
    "Kochi",
    "Kozhikode",
    "Thrissur",
    "Kollam",
    "Palakkad",
    "Alappuzha",
    "Kannur",
    "Kottayam",
    "Malappuram",
    "Kasaragod",
  ],
  Gujarat: [
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
    "Junagadh",
    "Gandhinagar",
    "Anand",
    "Navsari",
    "Bharuch",
    "Mehsana",
  ],
  Delhi: [
    "New Delhi",
    "Central Delhi",
    "East Delhi",
    "North Delhi",
    "North East Delhi",
    "North West Delhi",
    "Shahdara",
    "South Delhi",
    "South East Delhi",
    "South West Delhi",
    "West Delhi",
    "Noida",
    "Gurgaon",
    "Ghaziabad",
    "Faridabad",
  ],
  "West Bengal": [
    "Kolkata",
    "Howrah",
    "Durgapur",
    "Asansol",
    "Siliguri",
    "Bardhaman",
    "Malda",
    "Kharagpur",
    "Haldia",
    "Jalpaiguri",
  ],
  Rajasthan: [
    "Jaipur",
    "Jodhpur",
    "Kota",
    "Bikaner",
    "Ajmer",
    "Udaipur",
    "Bhilwara",
    "Alwar",
    "Sikar",
    "Bharatpur",
  ],
  "Uttar Pradesh": [
    "Lucknow",
    "Kanpur",
    "Ghaziabad",
    "Agra",
    "Varanasi",
    "Meerut",
    "Prayagraj (Allahabad)",
    "Bareilly",
    "Aligarh",
    "Moradabad",
    "Gorakhpur",
    "Noida",
  ],
  "Madhya Pradesh": [
    "Bhopal",
    "Indore",
    "Jabalpur",
    "Gwalior",
    "Ujjain",
    "Sagar",
    "Dewas",
    "Satna",
    "Ratlam",
    "Rewa",
  ],
  Odisha: [
    "Bhubaneswar",
    "Cuttack",
    "Rourkela",
    "Berhampur",
    "Sambalpur",
    "Puri",
    "Balasore",
    "Bhadrak",
  ],
  Punjab: [
    "Ludhiana",
    "Amritsar",
    "Jalandhar",
    "Patiala",
    "Bathinda",
    "Mohali",
    "Pathankot",
    "Hoshiarpur",
  ],
} as const;

/** Preset cities for any state name (case insensitive lookup) */
export function getPresetCitiesForState(stateName: string): string[] {
  const norm = stateName.trim().toLowerCase();
  const foundKey = Object.keys(STATE_DISTRICTS).find(
    (k) => k.toLowerCase() === norm,
  );
  if (foundKey) {
    return [...STATE_DISTRICTS[foundKey as keyof typeof STATE_DISTRICTS]];
  }
  return [];
}
